{
  imports = [
    ./audio-video-hardware.nix
    ./autologin.nix
    ./bootloader.nix
    ./devstuff.nix
    ./disks.nix
    ./docker.nix
    ./env.nix
    ./external-hardware.nix
    ./fonts.nix
    ./host-base.nix
    ./hyprland.nix
    ./keyboard.nix
    ./keyd.nix
    ./neovim.nix
    ./networking.nix
    ./nixx.nix
    ./pam.nix
    ./pkgs-base.nix
    ./qt.nix
    ./steam.nix
    ./theme.nix
    ./thumbnails/thumbnails.nix
  ];
}
