# vim: filetype=hyprlang

input {
    kb_layout = us,gr
    kb_variant = 
    kb_model =
    kb_options=compose:ralt 
    kb_rules =
    natural_scroll = true
	float_switch_override_focus = 2

	repeat_rate = 50
	repeat_delay = 250

    follow_mouse = 1

    touchpad {
        natural_scroll = true
		clickfinger_behavior = 1 # Two-finger click is rightclick
        disable_while_typing = true 
    }

	accel_profile = flat
    sensitivity = 0.0 # -1.0 - 1.0, 0 means no modification.
}

scrolling {
	
}


dwindle {
    pseudotile = true # master switch for pseudotiling. 
    preserve_split = true # you probably want this
    special_scale_factor = 0.8
}

master {
    new_status = inherit
    new_on_top=1
    mfact = 0.5
}


binds {
	workspace_back_and_forth =  false
	allow_workspace_cycles	 =  true
}

cursor {
}

ecosystem {
	no_donation_nag = true
}

misc {
	disable_splash_rendering = true
	force_default_wallpaper	= 0
	disable_hyprland_logo	= true
    focus_on_activate = false
    animate_manual_resizes = true
	close_special_on_empty = true
    enable_swallow = false
	swallow_regex = ^(kitty)$
}


decoration {
    rounding = 16
	rounding_power = 4


	dim_inactive = false
	dim_special = 0.2
    dim_strength = 0.06

	border_part_of_window = false
    
    blur {
        enabled = true
        size = 10
        passes = 3
        new_optimizations = true
        xray = false
		contrast = 2
		brightness = 0.80
		noise = 0.6
		vibrancy = 1
		vibrancy_darkness = 0.2
		special = false
		popups = true
        popups_ignorealpha = 0.6
    }

	shadow {
		enabled = true
		range = 120
		scale = 0.95
		render_power = 80
		offset = 0, 4 
		color = rgba(000000FC)
		color_inactive = rgba(00000050)
	}
}

debug {
	 # damage_tracking = 0 
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    layout = dwindle
    gaps_in = 3
    gaps_out = 6
	gaps_workspaces = 20
    border_size = 1
    col.active_border = rgba(212,190,152,0.70) rgba(212,190,152,0.3) 40deg
    col.inactive_border = rgba(168,153,132,0.06)
    resize_on_border = true

    snap {
    	enabled = true
    	window_gap = 4
    	monitor_gap = 5
    	respect_gaps = true
    }
}
# More space if there is only one tiled window
workspace = w[t1], gapsout:24

animations {
    # taken from end_4 
    enabled = true
	workspace_wraparound = false
    
    # Animation curves
    bezier = linear, 0, 0, 1, 1
    bezier = md3_standard, 0.2, 0, 0, 1
    bezier = md3_decel, 0.05, 0.7, 0.1, 1
    bezier = md3_accel, 0.3, 0, 0.8, 0.15
    bezier = overshot, 0.05, 0.9, 0.1, 1.1
    bezier = crazyshot, 0.1, 1.5, 0.76, 0.92 
    bezier = hyprnostretch, 0.05, 0.9, 0.1, 1.0
    bezier = menu_decel, 0.1, 1, 0, 1
    bezier = menu_accel, 0.38, 0.04, 1, 0.07
    bezier = easeInOutCirc, 0.85, 0, 0.15, 1
    bezier = easeOutCirc, 0, 0.55, 0.45, 1
    bezier = easeOutExpo, 0.16, 1, 0.3, 1
    bezier = softAcDecel, 0.26, 0.26, 0.15, 1
    bezier = md2, 0.4, 0, 0.2, 1 # use with .2s duration

    # Animation configs
    animation = windows, 1, 3, md3_decel, popin 60%
    animation = windowsIn, 1, 3, md3_decel, popin 60%
    animation = windowsOut, 1, 1.2, md3_accel, popin 60%
    animation = border, 0, 0.4, default
    animation = fade, 1, 3, md3_decel
    # animation = layers, 1, 2, md3_decel, slide
    animation = layersIn, 1, 4, menu_decel, slide
    animation = layersOut, 1, 1.2, menu_accel
    animation = fadeLayersIn, 1, 2, menu_decel
    animation = fadeLayersOut, 1, 0.5, menu_accel
    animation = workspaces, 1, 4, menu_decel, slide
	# animation = workspaces, 1, 2.5, softAcDecel, slide
    # animation = workspaces, 1, 7, menu_decel, slidefade 15%
    # animation = specialWorkspace, 1, 3, md3_decel, slidefadevert 15%
    animation = specialWorkspaceIn, 1, 4, md3_decel, slidevert
    animation = specialWorkspaceOut, 1, 1.2, md3_decel, slidevert
}

