# Subtitle size controls defaults
# Increase/decrease subtitle font size shift-g, shift-f

# Disable default right-click play/pause toggle.
MBTN_RIGHT ignore

# Scale video down/up
- add video-zoom -0.1
+ add video-zoom  0.1
