# Subtitle size controls defaults
# Increase/decrease subtitle font size shift-g, shift-f

# Disable default right-click play/pause toggle.
MBTN_RIGHT ignore

# Scale video down/up
- add video-zoom -0.1
+ add video-zoom  0.1


# Common
space        cycle pause; script-binding uosc/flash-pause-indicator
right        seek  5
left         seek -5
shift+right  seek  30; script-binding uosc/flash-timeline
shift+left   seek -30; script-binding uosc/flash-timeline
m            no-osd cycle mute; script-binding uosc/flash-volume
up           no-osd add volume  10; script-binding uosc/flash-volume
down         no-osd add volume -10; script-binding uosc/flash-volume
[            no-osd add speed -0.25; script-binding uosc/flash-speed
]            no-osd add speed  0.25; script-binding uosc/flash-speed
\            no-osd set speed 1; script-binding uosc/flash-speed
>            script-binding uosc/next; script-message-to uosc flash-elements top_bar,timeline
<            script-binding uosc/prev; script-message-to uosc flash-elements top_bar,timeline


# Toggle menus
s	script-binding uosc/subtitles
a	script-binding uosc/audio
p	script-binding uosc/items
c	script-binding uosc/chapters 

# Context menu
mbtn_right  script-binding uosc/menu
menu        script-binding uosc/menu
