sub-color="#FFBF00"
sub-border-color="#000000"
sub-border-size=3
sub-shadow-offset=1
sub-shadow-color="#000000"
sub-scale=0.9

alang = 'jpn,jp,eng,en'
slang = 'eng,en,enUS' # enUS for Crunchyroll.

keep-open=always # Prevents autoplay playlists. Set to 'yes' to autoload. Both "always" and "yes" prevents player from auto closing upon playback complete.
reset-on-next-file=pause # Resumes playback when skip to next file

window-scale=1.5 # Set video zoom factor. (High DPI screens want 1.5 or even 2)

no-osd-bar # Hide OSD bar when seeking.
osd-duration=500 # Hide OSD text after x ms.
osd-font='Trebuchet MS'
#osd-font-size=24
osd-bar=no
